### ISSUE TITLE
Fix the images in the slides about "Publish the dataset"

### ISSUE THREAD

**Issue by oeway** [imodpasteur/ShareLoc.XYZ#35]
@baiddd Please look into this issue.

**Comment by baiddd** [comment]
It’s fixed now

**Comment by oeway** [comment]
@baiddd I just checked, but it seems the issue is still there, I cannot see the images for some reason.
